# Generated by Django 2.1.5 on 2020-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=255)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'activityperiod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=255)),
                ('u_tz', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
