# Generated by Django 2.1.5 on 2020-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_timestamp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
